[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/gallery"
  to = "/gallery/"
  status = 301
  force = true

[[redirects]]
  from = "/gallery/*"
  to = "https://3dprintgallery.netlify.app/:splat"
  status = 200
  force = true
